# Generated by Django 3.0.5 on 2020-05-01 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post_category', models.CharField(choices=[('Personal Blog', 'Personal Blog'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('News', 'News'), ('Health', 'Health'), ('Art', 'Art'), ('Product', 'Product'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Lifestyle/Beauty', 'Lifestyle/Beauty'), ('Books', 'Books'), ('Food', 'Food')], default='Personal Blog', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], default='Draft', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
