# Generated by Django 3.0.5 on 2020-05-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='approved_comment',
        ),
    ]
