# Generated by Django 3.0.5 on 2020-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Java', 'Education'), ('Javascript', 'News'), ('HTML', 'Health'), ('CSS', 'Art'), ('Angular', 'Product'), ('REACT', 'Technology'), ('Node', 'Sports'), ('Databases', 'Lifestyle/Beauty'), ('Bootstrap', 'Books'), ('Databases', 'Food')], default='Personal Blog', max_length=30),
        ),
    ]
