# Generated by Django 3.0.5 on 2020-05-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200503_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('Pyramid', 'Pyramid'), ('RESTFramework', 'RESTFramework'), ('Javascript', 'Javascript'), ('Angular', 'Angular'), ('REACT', 'REACT'), ('Node', 'Node'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('Java', 'Java'), ('Databases', 'Databases')], default='Web Development', max_length=30),
        ),
    ]
