# Generated by Django 3.0.5 on 2020-05-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
