# Generated by Django 3.0.5 on 2020-05-03 12:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_article',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
