# Generated by Django 3.0.5 on 2020-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200503_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='about_article',
        ),
    ]
