# Generated by Django 3.0.5 on 2020-05-03 13:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_about_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_article',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
