# Generated by Django 3.0.5 on 2020-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_about_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='about_article',
        ),
    ]
