# Generated by Django 3.0.5 on 2020-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_about_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_article',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
