# Generated by Django 3.0.5 on 2020-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('Pyramid', 'Pyramid'), ('REST Framework', 'REST Framework'), ('Javascript', 'Javascript'), ('Angular', 'Angular'), ('REACT', 'REACT'), ('Node', 'Node'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('Java', 'Java'), ('Databases', 'Databases')], default='Web Development', max_length=30),
        ),
    ]
